export const AUTHENTICATE = 'AUTHENTICATE';
export const UNAUTHENTICATE = 'UNAUTHENTICATE';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL';
